[project]
name = "auto-coin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.86.0",
    "plotly>=6.1.2",
    "python-bithumb>=0.1.3",
    "python-dotenv>=1.1.0",
    "schedule>=1.2.2",
]
